project_id = "lmqyizrnuahkmwauonqr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lmqyizrnuahkmwauonqr.supabase.co"]
jwt_expiry = 3600
enable_signup = false

[auth.email]
enable_signup = false
double_confirm_changes = true

[db]
port = 54322

[functions.mpesa-stk-push]
verify_jwt = true

[functions.mpesa-callback]
verify_jwt = false

[functions.mpesa-validation]
verify_jwt = false

[functions.mpesa-confirmation]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[storage]
enabled = true
file_size_limit = "50MiB"

[studio]
enabled = true
port = 54323
